### PR TITLE
Add support for the Meson build system

### PR DESCRIPTION
**Pull request by nielsdg**
See the [Meson website] for a full reference. To build, test and/or
install ibus-m17n, you essentially need the following commands:

```
$ meson --prefix=/usr _build
$ meson compile -C _build
$ meson test -C _build
$ meson install -C _build
```

[Meson website]: http://mesonbuild.com/

### CODE REVIEW

**Comment by pnemade** [comment]
Why meson build system? Why not CMake?

**Comment by pnemade** [comment]
I am not familiar with Meson, no project I am looking into using Meson. However, I have used in the past CMake.
And here project maintainers are not familiar with Meson. So to me it looks difficult.

**Comment by nielsdg** [comment]
I can understand that. I can offer you guidance to learn to understand it, if you were interested.

In any case, it's up to you if you choose to accept or decline the PR :)

**Comment by nielsdg** [comment]
Ah, indeed, I was incorrect here, it should be good now :-)

**Pull request closed without merging**
